version: '3.7'

services:
  elasticsearch:
    build:
      context: docker/elasticsearch/
      dockerfile: Dockerfile
    volumes:
      - /usr/share/elasticsearch/data
    
  server:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - 5002:5000
    environment:
      - FLASK_CONFIG=development
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
    depends_on:
      - elasticsearch